configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cozmo-ai/cozmoai-141b25dfc76ab980ac81f206e7da0c2dca4b871dd5ceb1b229c7aaae61cca0b4.yml
openapi_spec_hash: dfdcf7f36372e31d917bf836b08f1db1
config_hash: 8d5c6291f34bbe7fbf355a881fffbaa6
